### ISSUE TITLE
Experience with GSSAPI mechanism on windows?

### ISSUE THREAD

**Issue by bquinart** [thobbs/pure-sasl#14]
Has anyone tried the GSSAPI mechanism on windows?
Is there any plans for this?

Thanks

**Comment by thobbs** [comment]
This library doesn't do anything that should be platform-specific -- it's just processing bytes that you pass to it and calling out to the kerberos library.  I think you probably want to focus on making sure the kerberos library works on windows.

**Comment by bquinart** [comment]
Thanks for your reply.
Indeed, I get in trouble with the kerberos library. Not pure-sasl itself.
Kerberos functionality is an important part of what this library offers,i'd like to understand if someone has this actually working on Windows.
