### ISSUE TITLE
Test requirement on mock is capped to <= 1.0.1

### ISSUE THREAD

**Issue by xavierba** [thobbs/pure-sasl#35]
Test requirement on mock is capped to <= 1.0.1

Is that still needed ? Tests are passing with mock 3.0.5.
It was already discussed here : https://github.com/thobbs/pure-sasl/pull/12/files#r51483902

https://github.com/thobbs/pure-sasl/blob/1543812abb46f961028c3a4f045189a92fc4e5ed/test-requirements.txt#L2

**Comment by thobbs** [comment]
The linked PR has been merged, so this should be fixed
