### ISSUE TITLE
winkerberos incorrect capitalization of 'N' has been fixed

### ISSUE THREAD

**Issue by andreostrovsky** [thobbs/pure-sasl#39]
> It is doing some magic, the winkerberos library has different capitalisation on the 'N' in name. this just makes it compatible.

_Originally posted by @ryan-pip in https://github.com/thobbs/pure-sasl/pull/30#discussion_r247614258_

This capitalization issue in winkerberos has been fixed. This line needs to be removed as currently it produces the following error:
`AttributeError: module 'winkerberos' has no attribute 'authGSSClientUsername'`

Using:
winkerberos=0.8.0
pure-sasl=0.6.2

**Comment by thobbs** [comment]
@andreostrovsky I have just merged #34. Could you please confirm this has resolved the issue?

**Comment by andreostrovsky** [comment]
Confirmed. Closing this issue.
